import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React from 'react'
import Head from 'next/head'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Eline | Template Graphic Designer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <Head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <body className={`${inter.className} max-w-[clac(min(100vw,1920px))] flex items-center justify-center flex-col overflow-x-hidden `}>{children}</body>
    </html>
  )
}
